services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: wptechnix-simple-logger-dev
    volumes:
      - .:/app
      - composer-cache:/tmp/composer
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  composer-cache:
